# Generated by Django 3.2 on 2021-04-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('total_per_hour', models.CharField(max_length=1024)),
                ('new', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Infected',
            fields=[
                ('metric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covmass.metric')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infected', to='covmass.zone')),
            ],
            bases=('covmass.metric',),
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('metric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covmass.metric')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deceased', to='covmass.zone')),
            ],
            bases=('covmass.metric',),
        ),
    ]
