# Generated by Django 3.2 on 2021-04-29 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covmass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deceased', to='covmass.zone'),
        ),
        migrations.AlterField(
            model_name='infected',
            name='zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infected', to='covmass.zone'),
        ),
    ]
