# Generated by Django 3.2 on 2021-04-30 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('new', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='covid.source')),
            ],
        ),
        migrations.CreateModel(
            name='Infected',
            fields=[
                ('metric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.metric')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infected', to='covid.zone')),
            ],
            bases=('covid.metric',),
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('metric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.metric')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deceased', to='covid.zone')),
            ],
            bases=('covid.metric',),
        ),
    ]
