# Generated by Django 3.2 on 2021-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
